eyebrow: "Наши услуги"
cards:
  - title: "<i>Качественные</i> исследования"
    front_text: >-
      фокус-группы, offline 1-to-1 опросы, UX/UI исследования, анализ
      аудитории, конкурентный анализ, mystery shopping
    back_text: >-
      Данные исследования предоставят полное понимание опыта, мнений и&nbsp;представлений
      текущих
      и&nbsp;потенциальных клиентов
    cta_label: "Заказать исследование"
    cta_href: "https://t.me/+77066396195"
  - title: "<i>Количественные</i> исследования"
    front_text: "Ad&nbsp;tracking, Brand Health Tracking online"
    back_text: >-
      Анализ данных, полученных с&nbsp;помощью большого количества опрошенных респондентов
      в&nbsp;ходе опроса или анкетирования
    cta_label: "Заказать исследование"
    cta_href: "https://t.me/+77066396195"
  - title: "<i>Маркетинговые</i> исследования"
    front_text: >-
      Позиции и&nbsp;перспективы на&nbsp;рынке, Размер рынка, Анализ конкурентов
      и&nbsp;аудитории, Анализ продуктовых и&nbsp;маркетинговых активностей,
      Sensitivity to&nbsp;pricing
    back_text: >-
      Поиск, сбор и&nbsp;анализ информации, которая обеспечивает потребности маркетинга
      компании
    cta_label: "Заказать исследование"
    cta_href: "https://t.me/+77066396195"
